modLoader="javafml"
loaderVersion="[0,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Tomate0613/revert-23w46a/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="" # https://docs.minecraftforge.net/en/latest/misc/updatechecker/
displayURL="https://modrinth.com/mod/revert-23w46a"
logoFile="icon.png"
#credits=""
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="SERVER"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
#[features.${mod_id}]
#openGLVersion="[3.2,)"